name: Build-and-Deploy
on: push
env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: wissem
                IMAGE_NAME: app
                DOCKER_PASSWORD: 123456789
jobs:
    docker-job:        
        runs-on: ubuntu-latest
        steps:
            - name: Build the image              
              run: echo docker build . -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME

            - name: login
              run: echo docker login -- username= $DOCKER_USERNAME --password = DOCKER_PASSWORD

            - name: Push the image
              run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME

    deploy-job:
        needs: docker-job
        runs-on: ubuntu-latest
        steps:
            - name: Run the app
              run: echo docker run $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME