name: multiple-jobs
on: push
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: build the app
        run: |
          sleep 3
          echo "building the app" >app.txt
      - name: upload the file app.txt    
        uses: actions/upload-artifact@v7
        with:
          name: app.txt file
          path: app.txt
        
  test-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
       - name: download the file app.txt    
         uses: actions/download-artifact@v8
         with:
            name: app.txt file
            path: app.txt       
             
      - name: Test the app
        run: |
          sleep 3
          cat app.txt
          echo "Testing the app"
     
  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:

      - name: download the file app.txt    
        uses: actions/download-artifact@v8
        with:
          name: app.txt file
          path: app.txt

      - name: deploy the app
        run: |
          sleep 3
          cat app.txt
          echo "deploying the app"

  